config/routes.rb
Rails.application.routes.draw do
  get '/user' => 'users#user'
  get '/user/:id/posts', to: 'users#user_posts', as: 'user_posts'
  get 'user/posts', to: 'users#my_posts', as: 'my_posts'
  get 'user/post/:id' => 'users#show'
  get '/user/favorite_posts', to: 'users#favorite_posts', as: 'favorite_posts'
  get '/user/aruaru_posts', to: 'users#aruaru_posts', as: 'aruaru_posts'
  get '/user/nainai_posts', to: 'users#nainai_posts', as: 'nainai_posts'
  devise_for :users
  resources :posts do
    member do
      post :aruaru
      post :nainai
    end
    resource :favorites, only: [:create, :destroy]
  end
  resources :comments 
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'homes#top'
  get '/search' => 'searches#search'
  root to: "searches#search"             
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/aruaru.rb
class Aruaru < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/nainai.rb
class Nainai < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags, dependent: :destroy
  has_many :comments
  has_many :favorites, dependent: :destroy 
  has_many :users, through: :favorites
  has_many :aruarus, dependent: :destroy
  has_many :aruaru_users, through: :aruarus, source: :user
  has_many :nainais, dependent: :destroy
  has_many :nainai_users, through: :nainais, source: :user
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags, dependent: :destroy

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "name", "updated_at"]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
  has_many :favorites, dependent: :destroy 
  has_many :favorite_posts, through: :favorites, source: :post 
  has_many :aruarus, dependent: :destroy
  has_many :aruaru_posts, through: :aruarus, source: :post
  has_many :nainais, dependent: :destroy
  has_many :nainai_posts, through: :nainais, source: :post

  def aruaru?(post_id, user_id)
    Aruaru.find_by(post_id: post_id, user_id: user_id)
  end
  
  def nainai?(post_id, user_id)
    Nainai.find_by(post_id: post_id, user_id: user_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create 
    Comment.create(comment_params)
    redirect_to request.referer
  end

  def update 
    comment = Comment.find(params[:comment][:comment_id])
    comment.update(comment_update_params)
    redirect_to request.referer
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to request.referer
  end

  private
  def comment_params
    params.require(:comment).permit(:text,:post_id).merge(user_id: current_user.id)
  end

  def comment_update_params 
    params.require(:comment).permit(:text)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy aruaru nainai ]
  before_action :authenticate_user!, only: %i[ new edit ]
  before_action :check_user, only: %i[  edit destroy ]
  before_action :data_for_aside, only: %i[ index show]

  # GET /posts or /posts.json
  def index
    @q = Tag.ransack(params[:q])
    @tag = @q.result.first
    if @tag
      @posts = @tag.posts.page(params[:page])
    else 
      @posts = Post.all.page(params[:page]).order(created_at: :DESC)
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comments = @post.comments.order(created_at: :desc)
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @form = PostsForm.new
  end

  # GET /posts/1/edit
  def edit
    @tag_list = @post.tags.pluck(:name).join("、")
    @form = PostsForm.new(post: @post)
  end

  # POST /posts or /posts.json
  def create
    @form = PostsForm.new(post_params)
    tag_list = params[:posts_form][:name].split("、")
    if @form.valid?
      @form.save(tag_list)
      redirect_to my_posts_path
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    @form = PostsForm.new(post_update_params, post: @post)
    tag_list = params[:posts_form][:name].split("、")
    if @form.update(tag_list)
      redirect_to my_posts_path
    else
      render :edit
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    redirect_to my_posts_path
  end

  def aruaru
    Aruaru.create(post_id: params[:id], user_id: current_user.id)
  end

  def nainai
    Nainai.create(post_id: params[:id], user_id: current_user.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def check_user
      redirect_to users_my_posts_path unless @post.user.id == current_user.id
    end

    def data_for_aside
      @users = User.all
      @tag_hash = Tag.joins(:post_tags).group('tags.name').order('count_post_id desc').count(:post_id).take(10).to_h
    end

    def post_update_params
      params.require(:posts_form).permit(:content, :name).merge(user_id: current_user.id, post_id: params[:id])    
    end
  

    def post_params
      params.require(:posts_form).permit(:content, :name).merge(user_id: current_user.id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:user_posts]
  def user
  end

  def user_posts
    @user = User.find(params[:id])
  end

  def my_posts
    @posts = current_user.posts.order(created_at: :DESC)
  end

  def favorite_posts
    @posts = current_user.favorite_posts
  end

  def aruaru_posts
    @posts = current_user.aruaru_posts
  end

  def nainai_posts
    @posts = current_user.nainai_posts
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @users = User.all
    @tag_hash = Tag.joins(:post_tags).group('tags.name').order('count_post_id desc').count(:post_id).take(9).to_h
    redirect_to my_posts_path unless @post.user.id == current_user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AruaruApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v6.2.0/css/all.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kosugi+Maru&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width,initial-scale=1">
  </head>

  <body>
  <header>
  <div class="header">
    <h1 class="title"><a href="/">あるある広場</a></h1>
    <nav class="icon">
      <ul>
      <li><%= render 'searches/searchform' %></li>
      <li><a href="/posts/new" class="home"><i class="fas fa-pencil-alt fa-lg"></i></a></li>
      <li><a href="/user" class="home"><%= image_tag 'Eric-cartman.png' %></a></li>
      </ul>
    </nav>
  </div>
  </header>
    <%= yield %>
  <div class="create-comment">
    <%= render 'searches/searchform' %>
  </div>
  <nav class="icon-iphone">
    <a class="home"><i class="fa-sharp fa-solid fa-house fa-lg"></i></a>
    <a href="/posts/new" class="home"><i class="fas fa-pencil-alt fa-lg"></i></a>
    <a href="/user" class="home"><%= image_tag 'Eric-cartman.png' %></a>
  </nav>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/partial_template/_aside.html.erb
<aside>
  <div class="ads">
    <ul>
    <li>注目のタグ</li>
    <% tag_hash.each do |tag_name, count| %>
    <li><%= link_to "##{tag_name} #{count}件", "/posts?utf8=✓&q%5Bname_cont%5D=#{tag_name}&button=" %></li>
    <% end %>
    </ul>
  </div>
  <div class="user-ranking">
    <ul>
    <li>あるある取得ランキング</li>
    <% users.each_with_index do |user,i|%>
      <li>
      <p class="user-area"><%= i+1 %>.<%= image_tag 'Eric-cartman.png' %>
      <% if user_signed_in? %>
        <% if user.id == current_user.id %>
        <%= link_to user.name, my_posts_path %>
        <% else %>
        <%= link_to user.name, user_posts_path(user) %>
        <% end %>
      <% else %>
        <%= link_to user.name, user_posts_path(user) %>
      <% end %>
      </p>
      </li>
    <% end %>
    </ul>
  </div>
</aside>

app/views/partial_template/_btn-area.html.erb
<%= link_to "あるある", "#!", class: "aruaru-btn" %>
<%= link_to "ないない", "#!", class: "nainai-btn" %>

app/views/partial_template/_comment.html.erb
<% if user_signed_in? %>
<li>
  <div class="user_area">
  <div class="post-user">
    <%= image_tag 'Eric-cartman.png' %>
    <% if comment.user.id == current_user.id %>
    <%= link_to comment.user.name, my_posts_path, class: "user-name" %>
    <% else %>
    <%= link_to comment.user.name, user_posts_path(comment.user), class: "user-name" %>
    <% end %>
    <p><%= time_ago_in_words(comment.created_at) %>前</p>
  </div>
  <div class="action-menu">
    <% if comment.user.id == current_user.id %>
    <div class="comment_edit_or_destroy">
      <p class="comment_edit_button"><i class="fa-solid fa-pen-to-square"></i></p>
      <p class="edit_cancel" style="display: none">キャンセル</p>
      <%= link_to comment_path(comment.id), method: :delete, class: "comment_destroy", data: { confirm: "本当に削除しますか？" } do %>
        <i class="fa-solid fa-trash-can"></i>
      <% end %>
    </div>
    <% else %>
    <i class="fa-solid fa-bullhorn"></i>
    <% end %>
  </div>
  </div>
  <p class="comment_text"><%= comment.text %></p>
  <%= form_with model: comment, url:comment_path, method: :PATCH, class: "comment_edit" do |f| %>
    <%= f.text_area :text, class: "input-comment" %>
    <%= f.hidden_field :comment_id, value: comment.id %>
    <div class="button">
      <%= f.submit "更新", class: "create-button" %>
    </div>
  <% end %>
</li>
<% else %>
<li>
  <div class="user_area">
    <div class="post-user">
      <%= image_tag 'Eric-cartman.png' %>
      <%= link_to comment.user.name, user_posts_path(comment.user), class: "user-name" %>
      <p><%= time_ago_in_words(comment.created_at) %>前</p>
    </div>
    <div class="action-menu">
      <i class="fa-solid fa-bullhorn"></i>
    </div>
  </div>
  <p class="comment_text"><%= comment.text %></p>
</li>
<% end %>

app/views/partial_template/_count-area.html.erb
<p class="aruaru-count">+<%= Aruaru.where(post_id: post.id).count %></p>
<p class="nainai-count">-<%= Nainai.where(post_id: post.id).count %></p>

app/views/partial_template/_favorites.html.erb
<% if user_signed_in? %>
  <% if current_user.favorites.find_by(post_id: post.id) %>
    <%= link_to post_favorites_path(post.id), method: :delete, remote: true do %>
      <i class="fas fa-star yellow-star"></i>
    <% end %>
  <% else %>
    <%= link_to post_favorites_path(post.id), method: :post, remote: true do %>
      <i class="fas fa-star black-star"></i>
    <% end %>
  <% end %>
<% else %>
  <%= link_to new_user_session_path do %>
    <i class="fas fa-star black-star"></i>
  <% end %>
<% end %>

app/views/partial_template/_function.html.erb
<div class="function">
  <div class="btn-area btn_area_<%= post.id %>">
  <% if user_signed_in? %>
    <% if current_user.aruaru?(post.id,current_user.id) or current_user.nainai?(post.id,current_user.id) %>
      <%= link_to "あるある", "#!", class: "aruaru-btn" %>
      <%= link_to "ないない", "#!", class: "nainai-btn" %>
    <% else %>
      <%= link_to "あるある", aruaru_post_path(post), method: :post, class: "aruaru-btn", remote: true %>
      <%= link_to "ないない", nainai_post_path(post), method: :post, class: "nainai-btn", remote: true %>
    <% end %>
  <% else %>
    <%= link_to "あるある", new_user_session_path, class: "aruaru-btn" %>
    <%= link_to "ないない", new_user_session_path, class: "nainai-btn" %>
  <% end %>
  </div>
  <div class="count-area count_area_<%= post.id %>">
    <p class="aruaru-count">+<%= Aruaru.where(post_id: post.id).count %></p>
    <p class="nainai-count">-<%= Nainai.where(post_id: post.id).count %></p>
  </div>
  <div class="footer-area">
    <div class="posted-date">
      <p><%= time_ago_in_words(post.created_at) %>前</p>
    </div>
    <div class="other-btn">
      <a href=""><i class="far fa-comment fa-lg"></i> <%= post.comments.count %></a>
      <div class="favorites", id="favorite_<%= post.id %>">
        <%= render 'partial_template/favorites', post: post %>
      </div>
    </div>
  </div>
</div>

app/views/partial_template/_post.html.erb
<div class="post">
<% if action_name == 'user_posts' %>
  <a href="/posts/<%= post.id %>", class="to_detail"></a>
  <p class="user-area"><%= image_tag 'Eric-cartman.png' %><%= post.user.name %></p>
<% elsif action_name == 'my_posts' %>
  <a href="/user/post/<%= post.id %>", class="to_detail"></a>
  <p class="user-area"><%= image_tag 'Eric-cartman.png' %><%= post.user.name %></p>
<% else %>
  <a href="/posts/<%= post.id %>", class="to_detail"></a>
  <p class="user-area"><%= image_tag 'Eric-cartman.png' %>
  <% if user_signed_in? %>
    <% if post.user.id == current_user.id %>
      <%= link_to post.user.name, user_path %>
    <% else %>
      <%= link_to post.user.name, user_posts_path(post.user) %>
    <% end %>
  <% else %>
    <%= link_to post.user.name, user_posts_path(post.user) %>
  <% end %>
  </p>
<% end %>
  <p class="text">
    <%= post.content %><br><br>
    <% post.tags.each do |tag| %>
      <span class="tag-name">#<%= link_to tag.name, "/posts?utf8=✓&q%5Bname_cont%5D=#{tag.name}&button=" %></span>
    <% end %>
  </p>
  <%= render 'partial_template/function', post: post %>
</div>

app/views/partial_template/_post_function.html.erb
<p class="user-area"><%= image_tag 'Eric-cartman.png' %><%= link_to post.user.name, user_posts_path %></p>
<%= link_to post.content, "/posts/#{post.id}", class: "text" %>
<div class="function">
  <div class="btn-area">
  <% if current_user.aruaru?(post.id,current_user.id) or current_user.nainai?(post.id,current_user.id) %>
    <%= link_to "あるある", "#!", class: "aruaru-btn" %>
    <%= link_to "ないない", "#!", class: "nainai-btn" %>
  <% else %>
    <%= link_to "あるある", aruaru_post_path(post), method: :post, class: "aruaru-btn", remote: true %>
    <%= link_to "ないない", nainai_post_path(post), method: :post, class: "nainai-btn", remote: true %>
  <% end %>
  </div>
  <div class="count-area">
    <p class="aruaru-count">+<%= Aruaru.where(post_id: post.id).count %></p>
    <p class="nainai-count">-<%= Nainai.where(post_id: post.id).count %></p>
  </div>
  <div class="footer-area">
    <div class="tag-area">
      <% post.post_tags.each do |post_tag| %>
        <p class="tag-name">#<%= post_tag.tag.name %></p>
      <% end %>
    </div>
    <div class="other-btn">
      <a href="/posts/1"><i class="far fa-comment fa-lg"></i></a>
      <a href=""><i class="fas fa-star fa-lg"></i></a>
    </div>
  </div>
</div>