config/routes.rb
Rails.application.routes.draw do
  get '/user' => 'users#user'
  get '/user/:id/posts', to: 'users#user_posts', as: 'user_posts'
  get 'user/posts', to: 'users#my_posts', as: 'my_posts'
  get 'user/post/:id' => 'users#show'
  get '/user/favorite_posts', to: 'users#favorite_posts', as: 'favorite_posts'
  get '/user/aruaru_posts', to: 'users#aruaru_posts', as: 'aruaru_posts'
  get '/user/nainai_posts', to: 'users#nainai_posts', as: 'nainai_posts'
  devise_for :users
  resources :posts do
    member do
      post :aruaru
      post :nainai
    end
    resource :favorites, only: [:create, :destroy]
  end
  resources :comments 
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'homes#top'
  get '/search' => 'searches#search'
  root to: "searches#search"             
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/aruaru.rb
class Aruaru < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/nainai.rb
class Nainai < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags, dependent: :destroy
  has_many :comments
  has_many :favorites, dependent: :destroy 
  has_many :users, through: :favorites
  has_many :aruarus, dependent: :destroy
  has_many :aruaru_users, through: :aruarus, source: :user
  has_many :nainais, dependent: :destroy
  has_many :nainai_users, through: :nainais, source: :user
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags, dependent: :destroy

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "name", "updated_at"]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
  has_many :favorites, dependent: :destroy 
  has_many :favorite_posts, through: :favorites, source: :post 
  has_many :aruarus, dependent: :destroy
  has_many :aruaru_posts, through: :aruarus, source: :post
  has_many :nainais, dependent: :destroy
  has_many :nainai_posts, through: :nainais, source: :post

  def aruaru?(post_id, user_id)
    Aruaru.find_by(post_id: post_id, user_id: user_id)
  end
  
  def nainai?(post_id, user_id)
    Nainai.find_by(post_id: post_id, user_id: user_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller? 
  before_action :search

  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email]) 
    end

    def search
      @q = Tag.ransack(params[:q])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create 
    Comment.create(comment_params)
    redirect_to request.referer
  end

  def update 
    comment = Comment.find(params[:comment][:comment_id])
    comment.update(comment_update_params)
    redirect_to request.referer
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to request.referer
  end

  private
  def comment_params
    params.require(:comment).permit(:text,:post_id).merge(user_id: current_user.id)
  end

  def comment_update_params 
    params.require(:comment).permit(:text)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_post 

  def create
    @favorite = Favorite.new(user_id: current_user.id,  post_id: @post.id)
    @favorite.save
  end

  def destroy
    @favorite = Favorite.find_by(user_id: current_user.id, post_id:  @post.id)
    @favorite.destroy
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy aruaru nainai ]
  before_action :authenticate_user!, only: %i[ new edit ]
  before_action :check_user, only: %i[  edit destroy ]
  before_action :data_for_aside, only: %i[ index show]

  # GET /posts or /posts.json
  def index
    @q = Tag.ransack(params[:q])
    @tag = @q.result.first
    if @tag
      @posts = @tag.posts.page(params[:page])
    else 
      @posts = Post.all.page(params[:page]).order(created_at: :DESC)
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comments = @post.comments.order(created_at: :desc)
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @form = PostsForm.new
  end

  # GET /posts/1/edit
  def edit
    @tag_list = @post.tags.pluck(:name).join("、")
    @form = PostsForm.new(post: @post)
  end

  # POST /posts or /posts.json
  def create
    @form = PostsForm.new(post_params)
    tag_list = params[:posts_form][:name].split("、")
    if @form.valid?
      @form.save(tag_list)
      redirect_to my_posts_path
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    @form = PostsForm.new(post_update_params, post: @post)
    tag_list = params[:posts_form][:name].split("、")
    if @form.update(tag_list)
      redirect_to my_posts_path
    else
      render :edit
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    redirect_to my_posts_path
  end

  def aruaru
    Aruaru.create(post_id: params[:id], user_id: current_user.id)
  end

  def nainai
    Nainai.create(post_id: params[:id], user_id: current_user.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def check_user
      redirect_to users_my_posts_path unless @post.user.id == current_user.id
    end

    def data_for_aside
      @users = User.all
      @tag_hash = Tag.joins(:post_tags).group('tags.name').order('count_post_id desc').count(:post_id).take(10).to_h
    end

    def post_update_params
      params.require(:posts_form).permit(:content, :name).merge(user_id: current_user.id, post_id: params[:id])    
    end
  

    def post_params
      params.require(:posts_form).permit(:content, :name).merge(user_id: current_user.id)
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:user_posts]
  def user
  end

  def user_posts
    @user = User.find(params[:id])
  end

  def my_posts
    @posts = current_user.posts.order(created_at: :DESC)
  end

  def favorite_posts
    @posts = current_user.favorite_posts
  end

  def aruaru_posts
    @posts = current_user.aruaru_posts
  end

  def nainai_posts
    @posts = current_user.nainai_posts
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @users = User.all
    @tag_hash = Tag.joins(:post_tags).group('tags.name').order('count_post_id desc').count(:post_id).take(9).to_h
    redirect_to my_posts_path unless @post.user.id == current_user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/create.js.erb
$("#favorite_<%= @post.id %>").html("<%= j(render 'partial_template/favorites', post: @post) %>");

app/views/favorites/destroy.js.erb
$("#favorite_<%= @post.id %>").html("<%= j(render 'partial_template/favorites', post: @post) %>");

app/views/posts/_form.html.erb
<main id="new-page">
  <div class="create-box">
    <% if form == @form %>
    <%= form_with model: form, url:posts_path do |f| %>
    <% else %>
    <%= form_with model: form, url:post_path, method: :patch do |f| %>
    <% end %>
      <div class="text-box">
        <%= f.label :content, "・テキスト", class: "text-label" %>
        <%= f.text_area :content, class: "content", placeholder: "授業中先生掃除しがち" %>
      </div>
      <div class="tag-box">
        <%= f.label :name, "・タグ", class: "tag-label" %>
        <%= f.text_area :name, class: "tag", placeholder: "(例)学校" %>
      </div>
      <%= f.submit "投稿", class: "create-button" %>
    <% end %>
  </div>
</main>

app/views/posts/aruaru.js.erb
$(".btn_area_<%= @post.id %>").html("<%= j(render 'partial_template/btn-area') %>");
$(".count_area_<%= @post.id %>").html("<%= j(render 'partial_template/count-area', post: @post) %>");

app/views/posts/edit.html.erb
<main id="new-page">
  <div class="create-box">
    <%= form_with model: @form, url:post_path, method: :patch do |f| %>
      <p class="user-area"><%= image_tag 'Eric-cartman.png' %><%= link_to current_user.name, user_posts_path %></p>
      <%= f.text_area :content, class: "content", placeholder: "テキスト" %>
      <%= f.text_area :name, class: "tag", placeholder: "タグ" %>
      <%= f.submit "更新", class: "create-button" %>
    <% end %>
  </div>
</main>

app/views/posts/index.html.erb
<main id="page">
  <div class="container">
    <div class="header-field">
      <% if @tag %>
      <p class="post-number">#<%= @tag.name %> <%= @posts.count %>件</p>
      <% else %>
      <p class="post-number">検索されたワードの投稿はありませんでした</p>
      <% end %>
    </div>
    <div class="box">
      <div class="index-main">
        <div class="posts-area"><%= render partial: 'partial_template/post', collection: @posts %></div>
        <%= paginate @posts, theme: 'twitter-bootstrap-4' %>
      </div>
      <%= render 'partial_template/aside',  {tag_hash: @tag_hash, users: @users} %>
    </div>
  </div>
</main>

app/views/posts/nainai.js.erb
$(".btn_area_<%= @post.id %>").html("<%= j(render 'partial_template/btn-area') %>");
$(".count_area_<%= @post.id %>").html("<%= j(render 'partial_template/count-area', post: @post) %>");

app/views/posts/new.html.erb
<main id="new-page">
  <div class="create-box">
    <%= form_with model: @form, url:posts_path do |f| %>
      <p class="user-area"><%= image_tag 'Eric-cartman.png' %><%= current_user.name %></p>
      <%= f.text_area :content, class: "content", placeholder: "テキスト" %>
      <%= f.text_area :name, class: "tag", placeholder: "タグ（複数入力する際は「、」で区切ってください）" %>
      <%= f.submit "投稿", class: "create-button" %>
    <% end %>
  </div>
</main>

app/views/posts/show.html.erb
<main id="show-page">
  <div class="container">
    <div class="box">
      <div class="show-main">
        <div class="post-show-area">
          <div class="post-detail">
            <p class="user-area">
            <%= image_tag 'Eric-cartman.png' %>
            <% if user_signed_in? %>
              <% if @post.user.id == current_user.id %>
              <%= link_to @post.user.name, my_posts_path %>
              <% else %>
              <%= link_to @post.user.name, user_posts_path(@post.user) %>
              <% end %>
            <% else %>
              <%= link_to @post.user.name, user_posts_path(@post.user) %>
            <% end %>
            </p>
            <p class="text">
            <%= @post.content %><br><br>
            <% @post.tags.each do |tag| %>
              <span class="tag-name">#<%= link_to tag.name, "/posts?utf8=✓&q%5Bname_cont%5D=#{tag.name}&button=" %></span>
            <% end %>
            </p>
            <%= render 'partial_template/function', post: @post %>
          </div>
          <div class="comment-area">
            <ul>
            <li>コメント  <%= @comments.count %>件</li>
            <% if user_signed_in? %>
              <li>
              <%= form_with model: @comment, url:comments_path do |f| %>
                <div class="user-area">
                  <%= image_tag 'Eric-cartman.png' %>
                  <%= f.text_area :text, class: "input-comment", placeholder: "コメントを入力 ..." %>
                  <%= f.hidden_field :post_id, value: @post.id %>
                </div>
                <div class="button">
                  <%= f.submit "投稿", class: "create-button" %>
                </div>
              <% end %>
              </li>
            <% end %>
            <%= render partial: 'partial_template/comment', collection: @comments %>
            </ul>
          </div>
        </div>
      </div>
      <%= render 'partial_template/aside',  {tag_hash: @tag_hash, users: @users} %>
    </div>
  </div>
</main>

app/views/users/aruaru_posts.html.erb
<main id="user-page">
  <div class="container">
    <div class="user-name-area">
      <div>
      <%= image_tag 'Eric-cartman.png' %>
      <p><%= current_user.name %></p>
      </div>
    </div>
    <div class="user-box">
      <div class="user-menu">
        <ul>
        <li>アカウント設定</li>
        <li><%= link_to "自分の投稿", my_posts_path %></li>
        <li><%= link_to "お気に入り登録した投稿", favorite_posts_path %></li>
        <li class="selected"><%= link_to "あるあるした投稿", aruaru_posts_path %></li>
        <li><%= link_to "ないないした投稿", nainai_posts_path %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>
      <div class="index-main">
        <div class="posts-area">
        <%= render partial: 'partial_template/post', collection: @posts, as: 'post' %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/users/favorite_posts.html.erb
<main id="user-page">
  <div class="container">
    <div class="user-name-area">
      <div>
      <%= image_tag 'Eric-cartman.png' %>
      <p><%= current_user.name %></p>
      </div>
    </div>
    <div class="user-box">
      <div class="user-menu">
        <ul>
        <li>アカウント設定</li>
        <li><%= link_to "自分の投稿", my_posts_path %></li>
        <li class="selected"><%= link_to "お気に入り登録した投稿", favorite_posts_path %></li>
        <li><%= link_to "あるあるした投稿", aruaru_posts_path %></li>
        <li><%= link_to "ないないした投稿", nainai_posts_path %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>
      <div class="index-main">
        <div class="posts-area">
        <%= render partial: 'partial_template/post', collection: @posts, as: 'post' %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/users/my_posts.html.erb
<main id="user-page">
  <div class="container">
    <div class="user-name-area">
      <div>
      <%= image_tag 'Eric-cartman.png' %>
      <p><%= current_user.name %></p>
      </div>
    </div>
    <div class="user-box">
      <div class="user-menu">
        <ul>
        <li>アカウント設定</li>
        <li class="selected"><%= link_to "自分の投稿", my_posts_path %></li>
        <li><%= link_to "お気に入り登録した投稿", favorite_posts_path %></li>
        <li><%= link_to "あるあるした投稿", aruaru_posts_path %></li>
        <li><%= link_to "ないないした投稿", nainai_posts_path %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>
      <div class="index-main">
        <div class="posts-area">
        <%= render partial: 'partial_template/post', collection: @posts, as: 'post' %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/users/nainai_posts.html.erb
<main id="user-page">
  <div class="container">
    <div class="user-name-area">
      <div>
      <%= image_tag 'Eric-cartman.png' %>
      <p><%= current_user.name %></p>
      </div>
    </div>
    <div class="user-box">
      <div class="user-menu">
        <ul>
        <li>アカウント設定</li>
        <li><%= link_to "自分の投稿", my_posts_path %></li>
        <li><%= link_to "お気に入り登録した投稿", favorite_posts_path %></li>
        <li><%= link_to "あるあるした投稿", aruaru_posts_path %></li>
        <li class="selected"><%= link_to "ないないした投稿", nainai_posts_path %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>
      <div class="index-main">
        <div class="posts-area">
        <%= render partial: 'partial_template/post', collection: @posts, as: 'post' %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main id="show-page">
  <div class="container">
    <div class="box">
      <div class="show-main">
        <div class="post-show-area">
          <div class="post-detail">
            <div class="user_area">
              <div class="post-user">
                <%= image_tag 'Eric-cartman.png' %><%= link_to @post.user.name, my_posts_path %>
              </div>
              <div class="edit-or-destroy">
                <%= link_to edit_post_path(@post) do %>
                  <i class="fa-solid fa-pen-to-square"></i>
                <% end %>
                <%= link_to post_path(@post), method: :delete, data: { confirm: "本当に削除しますか？" } do %>
                  <i class="fa-solid fa-trash-can"></i>
                <% end %>
              </div>
            </div>
            <p class="text">
            <%= @post.content %><br><br>
            <% @post.tags.each do |tag| %>
              <span class="tag-name">#<%= link_to tag.name, "/posts?utf8=✓&q%5Bname_cont%5D=#{tag.name}&button=" %></span>
            <% end %>
            </p>
            <%= render 'partial_template/function', post: @post %>
          </div>
          <div class="comment-area">
            <ul>
            <li>コメント  <%= @comments.count %>件</li>
            <%= render partial: 'partial_template/comment', collection: @comments %>
            </ul>
          </div>
        </div>
      </div>
      <%= render 'partial_template/aside',  {tag_hash: @tag_hash, users: @users} %>
    </div>
  </div>
</main>

app/views/users/user.html.erb
<main id="user-page">
  <div class="container">
    <div class="user-name-area">
      <div>
      <%= image_tag 'Eric-cartman.png' %>
      <p><%= current_user.name %></p>
      </div>
    </div>
    <div class="user-box">
      <div class="user-menu">
        <ul>
        <li>アカウント設定</li>
        <li><%= link_to "自分の投稿", my_posts_path %></li>
        <li><%= link_to "お気に入り登録した投稿", favorite_posts_path %></li>
        <li><%= link_to "あるあるした投稿", aruaru_posts_path %></li>
        <li><%= link_to "ないないした投稿", nainai_posts_path %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/users/user_posts.html.erb
<main id="user-page">
  <div class="container">
    <div class="user-name-area">
      <div>
      <%= image_tag 'Eric-cartman.png' %>
      <p><%= @user.name %></p>
      </div>
    </div>
    <div class="user-box">
      <div class="user-menu">
        <ul>
        <li>フォロー</li>
        </ul>
      </div>
      <div class="index-main">
        <div class="posts-area">
        <%= render partial: 'partial_template/post', collection: @user.posts, as: 'post' %>
        </div>
      </div>
    </div>
  </div>
</main>